set nocompatible
set ttyfast
set showmode
set showcmd
set title
set number
set hidden
set noerrorbells
set mouse=a
set nohlsearch
set nofoldenable

syntax enable
"filetype plugin indent on

" this is what files look like
set ffs=unix,dos,mac

" Update find path to search subdirectories
set path=$PWD/**

" No backups
set nobackup
set nowritebackup
set nowb
set noswapfile

" Keep a lot of history for undo
set undolevels=1000

" Files to ignore
" Python
set wildignore+=*.pyc,*.pyo,*/__pycache__/*
" Archives
set wildignore+=*.zip,*.tar

" Colors
set background=dark
"colorscheme anderson

" Tabs
set expandtab
set tabstop=4
set shiftwidth=4

autocmd Filetype bash setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd Filetype fish setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd Filetype fish compiler fish
autocmd Filetype fish setlocal textwidth=79
autocmd Filetype fish setlocal foldmethod=expr
autocmd Filetype make setlocal noexpandtab

" Plugins
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'dag/vim-fish'
" Plugin 'vim-airline/vim-airline'
" Plugin 'vim-airline/vim-airline-themes'
" Dev tools
Plugin 'tpope/vim-commentary'
Plugin 'neovim/nvim-lspconfig'
Plugin 'hrsh7th/cmp-nvim-lsp'
Plugin 'hrsh7th/cmp-buffer'
Plugin 'hrsh7th/cmp-path'
Plugin 'hrsh7th/cmp-cmdline'
Plugin 'hrsh7th/nvim-cmp'
Plugin 'hrsh7th/cmp-vsnip'
Plugin 'hrsh7th/vim-vsnip'
Plugin 'dense-analysis/ale'
Plugin 'davidhalter/jedi-vim'
" editor tools
Plugin 'nvim-lua/plenary.nvim'
Plugin 'nvim-telescope/telescope.nvim'
Plugin 'nvim-treesitter/nvim-treesitter'
Plugin 'kyazdani42/nvim-tree.lua'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'tanvirtin/vgit.nvim'
Plugin 'preservim/tagbar'
" Plugin 'tpope/vim-fugutive'
" Status line at bottom
Plugin 'nvim-lualine/lualine.nvim'
" Tab Bar for File
Plugin 'romgrk/barbar.nvim'
Plugin 'kyazdani42/nvim-web-devicons'

call vundle#end()
filetype plugin indent on

" Find files using Telescope command-line sugar
:let mapleader = " "
noremap <leader>ff <cmd>Telescope find_files<cr>
noremap <leader>fg <cmd>Telescope live_grep<cr>
noremap <leader>fb <cmd>Telescope buffers<cr>
noremap <leader>fh <cmd>Telescope help_tags<cr>

"" configure barbar
let bufferline = get(g:, "bufferline", {})
let bufferline.auto_hide = v:false
let bufferline.clickable = v:true

"" configure lualine
source ~/.vim/evil_lualine.vim

"" configure lsp
lua << END
require'lspconfig'.jedi_language_server.setup{}
END

"" configure Ale
let g:ale_linters = {
\   'python': ['pylint'],
\}
let g:ale_fixers = {
\   'python': ['black'],
\}
let g:ale_enabled = 0

"" configure cmp
set completeopt=menu,menuone,noselect
source ~/.vim/cmp_setup.vim

"" configure vgit
lua << EOF
require('vgit').setup()
vim.o.updatetime = 300
vim.o.incsearch = false
vim.wo.signcolumn = 'yes'
EOF

"" configure nvim-tree
source ~/.vim/nvim-tree.vim 

"" Load Keybindings
source ~/.vim/keybindings.vim
